/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author HENRY
 */
public class frmAcercaDe extends javax.swing.JDialog {

    /**
     * Creates new form frmAcercaDe
     */
    public frmAcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAcercaDe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAcercaProgramador = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAcercaAplicacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de");
        setResizable(false);

        lblAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/factura-electronica.png"))); // NOI18N
        lblAcercaDe.setMaximumSize(new java.awt.Dimension(300, 250));

        txtAcercaProgramador.setColumns(20);
        txtAcercaProgramador.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        txtAcercaProgramador.setForeground(new java.awt.Color(0, 0, 204));
        txtAcercaProgramador.setRows(4);
        txtAcercaProgramador.setText("Programador: Henry García Ospina \n\nCorreo:  henrygarcia0309@gmail.com");
        txtAcercaProgramador.setAutoscrolls(false);
        txtAcercaProgramador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAcercaProgramador.setEnabled(false);
        txtAcercaProgramador.setOpaque(false);
        jScrollPane1.setViewportView(txtAcercaProgramador);

        txtAcercaAplicacion.setEditable(false);
        txtAcercaAplicacion.setColumns(20);
        txtAcercaAplicacion.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        txtAcercaAplicacion.setRows(4);
        txtAcercaAplicacion.setText("Sistema de Facturación - 2018\n\nPereira (Risaralda)");
        txtAcercaAplicacion.setAutoscrolls(false);
        txtAcercaAplicacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAcercaAplicacion.setEnabled(false);
        txtAcercaAplicacion.setOpaque(false);
        jScrollPane2.setViewportView(txtAcercaAplicacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblAcercaDe.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmAcercaDe dialog = new frmAcercaDe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAcercaDe;
    private javax.swing.JTextArea txtAcercaAplicacion;
    private javax.swing.JTextArea txtAcercaProgramador;
    // End of variables declaration//GEN-END:variables
}
